# Generated by Django 4.1.3 on 2022-12-17 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticia.categoria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publicado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
